// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import redirectMap from './src/redirects.json' with { type: 'json' };

export default defineConfig({
  site: 'https://tribes2wiki.com',
  trailingSlash: 'never',
  /**
   * Links to the original tribes2wiki.com are still out in the world, so the old
   * MediaWiki URLs have to resolve. Generated by `npm run generate-redirects`.
   *
   * Titles containing a colon (`/wiki/Category:Armors`) are absent here on
   * purpose: a redirect page for those needs a directory with a colon in its
   * name, which is illegal on Windows. Those are handled by src/pages/404.astro.
   */
  redirects: redirectMap.static,
  integrations: [
    starlight({
      title: 'Tribes 2 Community Wiki',
      description:
        'The Community Tribes 2 Wiki — a community-maintained rebuild of tribes2wiki.com, ' +
        'recovered from the Internet Archive.',
      logo: {
        src: './src/assets/emblem.svg',
      },
      favicon: '/favicon.svg',
      customCss: ['./src/styles/theme.css'],
      social: [
        {
          icon: 'github',
          label: 'GitHub',
          href: 'https://github.com/Tribes2-Community/tribes2wiki',
        },
      ],
      editLink: {
        baseUrl: 'https://github.com/Tribes2-Community/tribes2wiki/edit/main/',
      },
      lastUpdated: true,
      /*
       * Starlight emits og:title, og:description and twitter:card, but no image,
       * so links unfurled on Discord, X and similar had no card to show. The
       * image is generated by `npm run make-og-image`.
       */
      head: [
        {
          tag: 'meta',
          attrs: { property: 'og:image', content: 'https://tribes2wiki.com/og.png' },
        },
        {
          tag: 'meta',
          attrs: { property: 'og:image:width', content: '1200' },
        },
        {
          tag: 'meta',
          attrs: { property: 'og:image:height', content: '630' },
        },
        {
          tag: 'meta',
          attrs: {
            property: 'og:image:alt',
            content: 'The Tribes 2 Community Wiki: the twin-fork emblem beside the site name.',
          },
        },
        {
          tag: 'meta',
          attrs: { name: 'twitter:image', content: 'https://tribes2wiki.com/og.png' },
        },
      ],
      // src/pages/404.astro replaces this: it doubles as the fallback router for
      // old tribes2wiki.com URLs that can't be emitted as static redirect pages.
      disable404Route: true,
      sidebar: [
        { label: 'Start here', items: [{ autogenerate: { directory: 'start' } }] },
        { label: 'Modern community', items: [{ autogenerate: { directory: 'community' } }] },
        { label: 'Weapons', items: [{ autogenerate: { directory: 'weapons' } }] },
        { label: 'Armors', items: [{ autogenerate: { directory: 'armors' } }] },
        { label: 'Packs & deployables', items: [{ autogenerate: { directory: 'equipment' } }] },
        {
          // Explicit rather than autogenerated: alphabetical order would put
          // Solar panel after Heavy offense, away from Generator, when the two
          // are read together.
          label: 'Base assets',
          items: [
            { slug: 'base-assets/category-base-assets' },
            { slug: 'base-assets/base-asset' },
            { slug: 'base-assets/base-turret' },
            { slug: 'base-assets/generator' },
            { slug: 'base-assets/solar-panel' },
            { slug: 'base-assets/pulse-sensor' },
            { slug: 'base-assets/heavy-offense' },
          ],
        },
        { label: 'Tactics', items: [{ autogenerate: { directory: 'tactics' } }] },
        { label: 'Maps & game types', items: [{ autogenerate: { directory: 'maps' } }] },
        { label: 'Community patches', items: [{ autogenerate: { directory: 'patches' } }] },
        { label: 'Scripting', items: [{ autogenerate: { directory: 'scripting' } }] },
        { label: 'Reference', items: [{ autogenerate: { directory: 'reference' } }] },
        { label: 'About this wiki', items: [{ autogenerate: { directory: 'project' } }] },
      ],
      components: {
        Footer: './src/components/Footer.astro',
      },
    }),
  ],
});
