// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import redirectMap from './src/redirects.json' with { type: 'json' };

export default defineConfig({
  site: 'https://tribes2wiki.com',
  trailingSlash: 'never',
  /**
   * Links to the original tribes2wiki.com are still out in the world, so the old
   * MediaWiki URLs have to resolve. Generated by `npm run generate-redirects`.
   *
   * Titles containing a colon (`/wiki/Category:Armors`) are absent here on
   * purpose: a redirect page for those needs a directory with a colon in its
   * name, which is illegal on Windows. Those are handled by src/pages/404.astro.
   */
  redirects: redirectMap.static,
  integrations: [
    starlight({
      title: 'Tribes2Wiki',
      description:
        'The Community Tribes 2 Wiki — a community-maintained rebuild of tribes2wiki.com, ' +
        'recovered from the Internet Archive.',
      logo: {
        src: './src/assets/emblem.svg',
      },
      favicon: '/favicon.svg',
      customCss: ['./src/styles/theme.css'],
      social: [
        {
          icon: 'github',
          label: 'GitHub',
          href: 'https://github.com/Tribes2-Community/tribes2wiki',
        },
      ],
      editLink: {
        baseUrl: 'https://github.com/Tribes2-Community/tribes2wiki/edit/main/',
      },
      lastUpdated: true,
      // src/pages/404.astro replaces this: it doubles as the fallback router for
      // old tribes2wiki.com URLs that can't be emitted as static redirect pages.
      disable404Route: true,
      sidebar: [
        { label: 'Start here', items: [{ autogenerate: { directory: 'start' } }] },
        { label: 'Weapons', items: [{ autogenerate: { directory: 'weapons' } }] },
        { label: 'Armors', items: [{ autogenerate: { directory: 'armors' } }] },
        { label: 'Packs & deployables', items: [{ autogenerate: { directory: 'equipment' } }] },
        { label: 'Base assets', items: [{ autogenerate: { directory: 'base-assets' } }] },
        { label: 'Tactics', items: [{ autogenerate: { directory: 'tactics' } }] },
        { label: 'Maps & game types', items: [{ autogenerate: { directory: 'maps' } }] },
        { label: 'Scripting', items: [{ autogenerate: { directory: 'scripting' } }] },
        { label: 'Reference', items: [{ autogenerate: { directory: 'reference' } }] },
        { label: 'About this wiki', items: [{ autogenerate: { directory: 'project' } }] },
      ],
      components: {
        Footer: './src/components/Footer.astro',
      },
    }),
  ],
});
