/**
 * Builds the old-URL -> new-route map so links to the original tribes2wiki.com
 * keep working.
 *
 * The original site served MediaWiki URLs: `/wiki/Fusion_mortar`,
 * `/wiki/Category:Armors`, and `/w/index.php5?title=Foo`. Those are still the
 * links that exist out in the world -- in forum posts, search results and the
 * Internet Archive -- so they must resolve.
 *
 * Two mechanisms, because of one filesystem constraint:
 *
 *   - `static`: emitted as real redirect pages via Astro's `redirects` config.
 *   - `all`:    the complete map, embedded in the 404 page as a client-side
 *               fallback.
 *
 * 17 of the 75 recovered pages have a colon in their title (`Category:Armors`).
 * A static redirect for those would need a directory literally named
 * `Category:Armors`, which is illegal on Windows and breaks the build there --
 * so colon URLs are served by the 404 fallback instead. Everything else gets a
 * real redirect page.
 */
import { writeFile, mkdir } from 'node:fs/promises';
import { readFileSync } from 'node:fs';
import path from 'node:path';

const REPORT = JSON.parse(readFileSync('archive/import-report.json', 'utf8'));
const OUT = path.join('src', 'redirects.json');

interface ReportPage {
  title: string;
  section: string;
  file: string;
}

function routeFor(page: ReportPage): string {
  const slug = path.basename(page.file, '.md');
  return slug === 'index' ? '/' : `/${page.section}/${slug}`;
}

/** The wiki wrote spaces as underscores in URLs. */
const toUrlTitle = (title: string) => title.replace(/ /g, '_');

/**
 * Pages removed after import because they duplicated another article. The
 * archive recorded them as separate pages -- the original wiki had both
 * `Mortar` and `Fusion mortar` carrying identical text -- so their old URLs are
 * pointed at the surviving article rather than at a route that no longer exists.
 */
const MERGED_PAGES: Record<string, string> = {
  Mortar: '/weapons/fusion-mortar',
};

const all: Record<string, string> = {};
const staticRedirects: Record<string, string> = {};

for (const page of REPORT.pages as ReportPage[]) {
  const target = MERGED_PAGES[page.title] ?? routeFor(page);
  const oldPath = `/wiki/${toUrlTitle(page.title)}`;

  all[oldPath] = target;
  if (!oldPath.includes(':')) staticRedirects[oldPath] = target;
}

// The original front page.
all['/wiki/Main_Page'] = '/';
staticRedirects['/wiki/Main_Page'] = '/';
all['/wiki'] = '/';
staticRedirects['/wiki'] = '/';

const output = {
  generatedAt: new Date().toISOString(),
  note:
    'Generated by scripts/generate-redirects.ts. `static` becomes real redirect ' +
    'pages; `all` is embedded in the 404 page, which also handles ?title= query ' +
    'URLs and colon titles that cannot be written to disk on Windows.',
  counts: {
    all: Object.keys(all).length,
    static: Object.keys(staticRedirects).length,
    fallbackOnly: Object.keys(all).length - Object.keys(staticRedirects).length,
  },
  static: staticRedirects,
  all,
};

await mkdir(path.dirname(OUT), { recursive: true });
await writeFile(OUT, `${JSON.stringify(output, null, 2)}\n`, 'utf8');

console.log('Wrote %s', OUT);
console.log('  %d old URLs mapped', output.counts.all);
console.log('  %d as static redirect pages', output.counts.static);
console.log('  %d served by the 404 fallback (colon in title)', output.counts.fallbackOnly);
