/**
 * Stage 4 of the import: turn the conversion report into MISSING_PAGES.md, the
 * community's worklist of articles lost when tribes2wiki.com went offline.
 *
 * Two different kinds of gap are tracked separately, because they need
 * different work:
 *   - lost pages    : the article existed and was linked, but no Wayback capture
 *                     survives. Someone has to rewrite it from knowledge.
 *   - never written : the original wiki linked the title in red. It was always a
 *                     gap, so this is a wishlist rather than a restoration.
 */
import { readFileSync, writeFileSync } from 'node:fs';

const report = JSON.parse(readFileSync('archive/import-report.json', 'utf8'));

/**
 * Page-view counts from the wiki's own Special:Statistics, captured 2010-11-07.
 * Useful for prioritising: these were the pages people actually read.
 * https://web.archive.org/web/20101107074741/http://www.tribes2wiki.com/wiki/Special:Statistics
 */
const ORIGINAL_VIEWS: Record<string, number> = {
  'Jericho mobile point base': 6829,
  Turret: 3492,
  'Sensor jammer pack': 3275,
};

const ORIGINAL_TOTALS = { contentPages: 121, uploadedFiles: 87 };

interface MissingPage {
  title: string;
  linkCount: number;
}

function table(rows: string[][], headers: string[]): string {
  const head = `| ${headers.join(' | ')} |`;
  const rule = `| ${headers.map(() => '---').join(' | ')} |`;
  return [head, rule, ...rows.map((r) => `| ${r.join(' | ')} |`)].join('\n');
}

const lost: MissingPage[] = report.missingPages;
const recovered: number = report.convertedPages;

const lostRows = lost.map((p) => {
  const views = ORIGINAL_VIEWS[p.title];
  return [
    p.title,
    String(p.linkCount),
    views ? `${views.toLocaleString('en-GB')} views` : '',
  ];
});

const redlinkRows = (report.redlinks as string[]).map((t) => [t]);

const imageRows = (report.missingImages as { file: string; useCount: number }[]).map((i) => [
  `\`${i.file}\``,
  String(i.useCount),
]);

const collisionRows = (report.slugCollisions as { slug: string; titles: string[] }[]).map((c) => [
  `\`${c.slug}\``,
  c.titles.map((t) => `\`${t}\``).join(' / '),
]);

const doc = `# Missing pages

The original tribes2wiki.com had **${ORIGINAL_TOTALS.contentPages} content pages** and
**${ORIGINAL_TOTALS.uploadedFiles} uploaded files**. The Internet Archive captured
**${recovered}** of those pages and only **2** of the images, so a little under half the
wiki has to be rewritten by the community.

This file is generated by \`npm run report-missing\`. Don't edit it by hand -- write the
article instead, and it will drop off the list on the next run.

## Lost articles (${lost.length})

These pages existed on the original wiki and were linked from articles we recovered, but
no capture of them survives. They need rewriting from knowledge. Sorted by how many
surviving articles link to them, so the most load-bearing gaps come first.

${table(lostRows, ['Page', 'Linked from', 'Original popularity'])}

## Never written (${report.redlinks.length})

The original wiki linked these titles in red -- they were always gaps. Treat this as a
wishlist rather than a restoration job.

${table(redlinkRows, ['Page'])}

## Lost images (${report.missingImages.length})

Referenced by surviving articles but lost with the site. Replacements for much of this
are available from community sources -- see \`src/assets/images/CREDITS.md\`.

${table(imageRows, ['File', 'Used by'])}
${
  collisionRows.length
    ? `
## Possible duplicates (${collisionRows.length})

Distinct titles on the original wiki that map to the same page name here. Both were kept;
someone should check whether they are genuinely two articles or a title that got
duplicated, and merge if so.

${table(collisionRows, ['Path', 'Original titles'])}
`
    : ''
}`;

writeFileSync('MISSING_PAGES.md', `${doc}\n`, 'utf8');

console.log('Wrote MISSING_PAGES.md');
console.log('  lost articles:  %d', lost.length);
console.log('  never written:  %d', report.redlinks.length);
console.log('  lost images:    %d', report.missingImages.length);
console.log('  duplicates:     %d', collisionRows.length);
